### PR TITLE
WIP: move agent package

### PR DESCRIPTION
**Pull request by sascha-andres**
Initial refactoring

- [ ] test from 3rd party application done yet

#66

### CODE REVIEW

**Comment by yohamta** [comment]
I am sorry, I accidentally used the same branch in another PR and deleted

**Comment by yohamta** [comment]
@sascha-andres Could you make this PR to main branch?

**Comment by sascha-andres** [comment]
@yohamta will update my fork and create a new PR

**Comment by yohamta** [comment]
Thanks!

**Pull request closed without merging**
